{{- range $key, $claim := dict "data" (include "ldap-manager.dataClaimName" .) "secrets" (include "ldap-manager.secretsClaimName" .) "cache" (include "ldap-manager.cacheClaimName" .) }}
{{- $p := index $.Values.persistence $key }}
{{- if and $p.enabled (not $p.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $claim }}
  labels:
    {{- include "ldap-manager.labels" $ | nindent 4 }}
  {{- with $p.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- toYaml $p.accessModes | nindent 4 }}
  {{- if $p.storageClass }}
  storageClassName: {{ $p.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ $p.size }}
{{- end }}
{{- end }}
