"""
Tests for LDAP Backup API (slapcat-style LDIF export)
"""

import pytest
from fastapi.testclient import TestClient
from app.main import app

client = TestClient(app)


def test_backup_status_endpoint():
    """Test backup status check endpoint."""
    # Note: This will fail without proper Keycloak token in production
    # For now, just test the endpoint exists
    response = client.get("/api/backup/status/test-cluster")

    # Expect 401 (unauthorized) in Keycloak mode or 404 (cluster not found) in legacy mode
    assert response.status_code in [401, 404, 200]


def test_backup_export_requires_auth():
    """Test that backup export requires authentication."""
    response = client.get("/api/backup/export/test-cluster")

    # Should require authentication
    assert response.status_code == 401


def test_ldif_export_format():
    """Test LDIF export formatting."""
    from app.api.backup import export_to_ldif
    from app.core.ldap_client import LDAPClient
    from unittest.mock import Mock

    # Mock LDAP client
    mock_client = Mock(spec=LDAPClient)

    # Mock search results
    mock_results = [
        (
            "dc=example,dc=com",
            {
                "objectClass": ["top", "dcObject", "organization"],
                "dc": ["example"],
                "o": ["Example Organization"],
            },
        ),
        (
            "ou=People,dc=example,dc=com",
            {
                "objectClass": ["organizationalUnit"],
                "ou": ["People"],
            },
        ),
    ]
    mock_client.search.return_value = mock_results

    # Export to LDIF
    ldif_content = export_to_ldif(mock_client, "dc=example,dc=com")

    # Verify LDIF format
    assert "version: 1" in ldif_content
    assert "dn: dc=example,dc=com" in ldif_content
    assert "objectClass: top" in ldif_content
    assert "dc: example" in ldif_content
    assert "dn: ou=People,dc=example,dc=com" in ldif_content
    assert "ou: People" in ldif_content

    # Verify header comments
    assert "# LDAP Directory Export (LDIF)" in ldif_content
    assert "# Generated by LDAP Manager" in ldif_content
    assert "# Base DN: dc=example,dc=com" in ldif_content


def test_ldif_base64_encoding():
    """Test that special characters are base64 encoded."""
    from app.api.backup import export_to_ldif
    from app.core.ldap_client import LDAPClient
    from unittest.mock import Mock

    mock_client = Mock(spec=LDAPClient)

    # Entry with special characters (non-ASCII)
    mock_results = [
        (
            "cn=Test User,dc=example,dc=com",
            {
                "cn": ["Test User"],
                "description": ["User with émojis 😀"],  # Non-ASCII
                "userPassword": [b"{SSHA}hashed..."],  # Binary
            },
        )
    ]
    mock_client.search.return_value = mock_results

    ldif_content = export_to_ldif(mock_client, "dc=example,dc=com")

    # Binary and non-ASCII should be base64 encoded (indicated by ::)
    assert "userPassword:: " in ldif_content  # Binary data
    assert "description:: " in ldif_content or "description: " in ldif_content  # May be base64


def test_backup_not_available_in_readonly_mode():
    """Test that backup is not available in read-only mode."""
    import os

    # Temporarily set read-only mode
    original_auth = os.getenv("AUTH_MODE")
    original_readonly = os.getenv("READONLY_MODE")

    os.environ["AUTH_MODE"] = "legacy"
    os.environ["READONLY_MODE"] = "true"

    try:
        # Reload app to pick up environment changes
        # (In real tests, this would be done with fixtures)

        # Backup should return 403 in read-only mode
        # (This test is conceptual - actual implementation would need proper setup)
        pass
    finally:
        # Restore original environment
        if original_auth:
            os.environ["AUTH_MODE"] = original_auth
        if original_readonly:
            os.environ["READONLY_MODE"] = original_readonly
