"""
LDAP Backup API - Export directory to LDIF format (slapcat-style)

Provides backup functionality similar to OpenLDAP's slapcat command.
Exports entire directory tree to LDIF (LDAP Data Interchange Format).

Access Control:
- Keycloak mode: Admin role required
- Read-write mode: Available to all users
- Read-only mode: Not available (403 Forbidden)
"""

from fastapi import APIRouter, Depends, HTTPException, Response
from app.core.auth import get_current_user, User
from app.core.rbac import admin_only
from app.core.config import load_config, get_cluster_config
from app.core.ldap_client import LDAPClient
from app.core.password_cache import get_password
from datetime import datetime
import logging
import os

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/backup", tags=["backup"])

AUTH_MODE = os.getenv("AUTH_MODE", "keycloak")
READONLY_MODE = os.getenv("READONLY_MODE", "false").lower() == "true"


def export_to_ldif(ldap_client: LDAPClient, base_dn: str) -> str:
    """
    Export entire LDAP directory to LDIF format.

    Similar to: slapcat -b "dc=example,dc=com"

    Args:
        ldap_client: Authenticated LDAP client
        base_dn: Base DN to export from

    Returns:
        LDIF formatted string

    LDIF Format:
        dn: cn=user,ou=People,dc=example,dc=com
        objectClass: inetOrgPerson
        cn: user
        sn: User
        mail: user@example.com

        dn: cn=admin,ou=People,dc=example,dc=com
        ...
    """
    logger.info(f"Starting LDIF export for base DN: {base_dn}")

    # Search for all entries under base DN
    # Use objectClass=* to get everything (like slapcat)
    search_filter = "(objectClass=*)"
    attributes = ["*", "+"]  # All user attributes + operational attributes

    try:
        results = ldap_client.search(
            base_dn=base_dn,
            search_filter=search_filter,
            attributes=attributes,
            scope=2  # SUBTREE scope
        )

        logger.info(f"Found {len(results)} entries to export")

        # Build LDIF content
        ldif_lines = []

        # Header comment
        ldif_lines.append(f"# LDAP Directory Export (LDIF)")
        ldif_lines.append(f"# Generated by LDAP Manager")
        ldif_lines.append(f"# Timestamp: {datetime.utcnow().isoformat()}Z")
        ldif_lines.append(f"# Base DN: {base_dn}")
        ldif_lines.append(f"# Total Entries: {len(results)}")
        ldif_lines.append(f"# Format: LDIF version 1")
        ldif_lines.append("")
        ldif_lines.append("version: 1")
        ldif_lines.append("")

        # Export each entry
        for dn, attrs in results:
            # DN line
            ldif_lines.append(f"dn: {dn}")

            # Attributes (sorted for consistency)
            for attr_name in sorted(attrs.keys()):
                attr_values = attrs[attr_name]

                # Handle single value or list
                if not isinstance(attr_values, list):
                    attr_values = [attr_values]

                # Write each value
                for value in attr_values:
                    # Handle bytes (binary data) - base64 encode
                    if isinstance(value, bytes):
                        import base64
                        encoded = base64.b64encode(value).decode('ascii')
                        ldif_lines.append(f"{attr_name}:: {encoded}")
                    else:
                        # Regular string value
                        # Escape special characters if needed
                        value_str = str(value)

                        # Check if value needs base64 encoding
                        # (contains non-ASCII or starts with special chars)
                        if (not value_str.isascii() or
                            value_str.startswith(' ') or
                            value_str.startswith(':') or
                            value_str.startswith('<')):
                            import base64
                            encoded = base64.b64encode(value_str.encode('utf-8')).decode('ascii')
                            ldif_lines.append(f"{attr_name}:: {encoded}")
                        else:
                            ldif_lines.append(f"{attr_name}: {value_str}")

            # Blank line between entries
            ldif_lines.append("")

        ldif_content = "\n".join(ldif_lines)

        logger.info(f"LDIF export completed: {len(ldif_lines)} lines, {len(ldif_content)} bytes")

        return ldif_content

    except Exception as e:
        logger.error(f"LDIF export failed: {e}", exc_info=True)
        raise HTTPException(status_code=500, detail=f"LDIF export failed: {str(e)}")


@router.get("/export/{cluster}")
async def export_ldif(
    cluster: str,
    user: User = Depends(get_current_user)
):
    """
    Export LDAP directory to LDIF format (slapcat-style backup).

    Creates a complete backup of the LDAP directory in LDIF format,
    similar to OpenLDAP's slapcat command.

    Access Control:
    - Keycloak mode: Admin role required
    - Read-write mode: Available to all users
    - Read-only mode: 403 Forbidden

    Returns:
        LDIF file download (application/x-ldif)
        Filename: {cluster}-{timestamp}.ldif

    Example:
        GET /api/backup/export/vibhuvioio.com

        Returns: vibhuvioio.com-20260130-120000.ldif

        Content:
        version: 1

        dn: dc=vibhuvioio,dc=com
        objectClass: top
        objectClass: dcObject
        objectClass: organization
        dc: vibhuvioio
        o: Vibhuvioio Organization

        dn: ou=People,dc=vibhuvioio,dc=com
        objectClass: organizationalUnit
        ou: People
        ...
    """
    # Access control check
    if AUTH_MODE == "legacy":
        if READONLY_MODE:
            # Read-only mode: Backup not allowed
            logger.warning(f"Backup attempt denied in read-only mode: user={user.username}")
            raise HTTPException(
                status_code=403,
                detail="Backup not available in read-only mode"
            )
        # Read-write mode: Allow all users
        logger.info(f"Backup export allowed in read-write mode: user={user.username}")
    else:
        # Keycloak mode: Admin only
        if not user.is_admin:
            logger.warning(f"Backup attempt denied for non-admin user: {user.username}")
            raise HTTPException(
                status_code=403,
                detail="Backup requires admin role"
            )
        logger.info(f"Backup export by admin user: {user.username}")

    # Load cluster configuration
    config = load_config()
    cluster_config = get_cluster_config(config, cluster)

    if not cluster_config:
        raise HTTPException(status_code=404, detail=f"Cluster '{cluster}' not found")

    # Get LDAP password from cache
    password = get_password(cluster, cluster_config.bind_dn)

    if not password:
        raise HTTPException(
            status_code=401,
            detail="LDAP connection not configured. Configure cluster connection first."
        )

    # Connect to LDAP
    try:
        # Use first node or single host
        if cluster_config.nodes:
            host = cluster_config.nodes[0].host
            port = cluster_config.nodes[0].port
        else:
            host = cluster_config.host
            port = cluster_config.port

        ldap_client = LDAPClient(
            host=host,
            port=port,
            bind_dn=cluster_config.bind_dn,
            bind_password=password,
            use_tls=cluster_config.use_tls
        )

        # Export to LDIF
        ldif_content = export_to_ldif(ldap_client, cluster_config.base_dn)

        # Generate filename with timestamp
        timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
        filename = f"{cluster}-{timestamp}.ldif"

        # Log the backup
        logger.info(
            "LDAP backup exported",
            extra={
                "user_id": user.user_id,
                "username": user.username,
                "cluster": cluster,
                "base_dn": cluster_config.base_dn,
                "filename": filename,
                "size_bytes": len(ldif_content),
                "operation": "BACKUP_EXPORT"
            }
        )

        # Return LDIF file as download
        return Response(
            content=ldif_content.encode('utf-8'),
            media_type="application/x-ldif",
            headers={
                "Content-Disposition": f'attachment; filename="{filename}"',
                "X-Cluster": cluster,
                "X-Export-Timestamp": timestamp,
                "X-Base-DN": cluster_config.base_dn
            }
        )

    except HTTPException:
        raise
    except Exception as e:
        logger.error(
            f"Backup export failed for cluster {cluster}: {e}",
            extra={
                "user_id": user.user_id,
                "username": user.username,
                "cluster": cluster,
                "error": str(e)
            },
            exc_info=True
        )
        raise HTTPException(
            status_code=500,
            detail=f"Backup export failed: {str(e)}"
        )


@router.get("/status/{cluster}")
async def backup_status(
    cluster: str,
    user: User = Depends(get_current_user)
):
    """
    Check if backup is available for the cluster.

    Returns cluster info and whether backup can be performed.

    Returns:
        {
            "cluster": "vibhuvioio.com",
            "backup_available": true,
            "base_dn": "dc=vibhuvioio,dc=com",
            "reason": "Admin access granted" | "Read-write mode" | "Not available in read-only mode"
        }
    """
    # Check access control
    backup_available = False
    reason = ""

    if AUTH_MODE == "legacy":
        if READONLY_MODE:
            reason = "Not available in read-only mode"
        else:
            backup_available = True
            reason = "Available in read-write mode"
    else:
        if user.is_admin:
            backup_available = True
            reason = "Admin access granted"
        else:
            reason = "Requires admin role"

    # Get cluster config
    config = load_config()
    cluster_config = get_cluster_config(config, cluster)

    if not cluster_config:
        raise HTTPException(status_code=404, detail=f"Cluster '{cluster}' not found")

    # Check if LDAP password is configured
    password = get_password(cluster, cluster_config.bind_dn)

    if not password and backup_available:
        backup_available = False
        reason = "LDAP connection not configured"

    return {
        "cluster": cluster,
        "backup_available": backup_available,
        "base_dn": cluster_config.base_dn,
        "reason": reason,
        "ldap_configured": password is not None
    }
